#!/usr/bin/env python3
"""Generate executive closure summary from structured compare CSV.

Reads compare output generated by Scripts/compare_eval_runs.py and fills
Docs/reports/resumen_cierre_v2_template.md placeholders.
"""

from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

import pandas as pd


def _to_num(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")


def _mean_str(series: pd.Series, digits: int = 2) -> str:
    s = _to_num(series)
    if not s.notna().any():
        return "N/A"
    return f"{s.mean():.{digits}f}"


def _sum_int_str(series: pd.Series) -> str:
    s = _to_num(series)
    if not s.notna().any():
        return "0"
    return str(int(round(float(s.sum()))))


def _smart_conclusion(cit_v1: int, cit_v2: int, ms_v1: float | None, ms_v2: float | None) -> tuple[str, str, str, str]:
    citation_delta = cit_v2 - cit_v1
    speed_msg = ""
    if ms_v1 is not None and ms_v2 is not None:
        if ms_v2 < ms_v1:
            speed_msg = "y mejora en latencia media"
        elif ms_v2 > ms_v1:
            speed_msg = "con mayor latencia media"
        else:
            speed_msg = "con latencia media estable"

    if citation_delta > 0:
        breve = f"v2 mejora trazabilidad de fuentes (+{citation_delta} citation tags) {speed_msg}".strip()
        impacto = "Mayor auditabilidad de respuestas structured por cita explícita de fuentes."
        riesgo = "Dependencia de cuota diaria del proveedor LLM para corridas completas."
        recomendacion = "Adoptar v2 como baseline structured y mantener monitoreo de rate limit."
    elif citation_delta == 0:
        breve = f"v2 no muestra mejora en citation tags {speed_msg}".strip()
        impacto = "Comportamiento estable frente a v1 en las métricas disponibles."
        riesgo = "Persisten respuestas sin trazabilidad explícita en parte de las consultas."
        recomendacion = "Iterar prompt de citación y validar nuevamente con compare final."
    else:
        breve = f"v2 retrocede en citation tags ({citation_delta}) {speed_msg}".strip()
        impacto = "Disminuye la trazabilidad explícita frente al baseline v1."
        riesgo = "Riesgo de menor auditabilidad para decisiones directivas."
        recomendacion = "No promover v2 a baseline hasta corregir instrucción de citación."

    return breve, impacto, riesgo, recomendacion


def main() -> None:
    parser = argparse.ArgumentParser(description="Fill resumen_cierre_v2 template from compare CSV")
    parser.add_argument("--compare", required=True, help="Path to structured v1 vs v2 compare CSV")
    parser.add_argument(
        "--template",
        default="Docs/reports/resumen_cierre_v2_template.md",
        help="Template markdown with placeholders",
    )
    parser.add_argument(
        "--output",
        default="Docs/reports/resumen_cierre_v2.md",
        help="Output markdown path",
    )
    parser.add_argument("--responsable", default="Equipo Observatorio CCHEN", help="Responsible person/team")
    parser.add_argument("--expected-queries", type=int, default=8, help="Expected number of structured queries")
    args = parser.parse_args()

    compare_path = Path(args.compare)
    template_path = Path(args.template)
    out_path = Path(args.output)

    if not compare_path.exists():
        raise SystemExit(f"[ERROR] compare CSV not found: {compare_path}")
    if not template_path.exists():
        raise SystemExit(f"[ERROR] template markdown not found: {template_path}")

    df = pd.read_csv(compare_path)
    n_queries = int(len(df))

    required = [
        "heuristic_citation_tags_v1",
        "heuristic_citation_tags_v2",
        "response_ms_v1",
        "response_ms_v2",
        "structured_available_source_ratio_v1",
        "structured_available_source_ratio_v2",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise SystemExit(f"[ERROR] compare CSV missing required columns: {', '.join(missing)}")

    citation_v1 = int(_sum_int_str(df["heuristic_citation_tags_v1"]))
    citation_v2 = int(_sum_int_str(df["heuristic_citation_tags_v2"]))
    citation_delta = citation_v2 - citation_v1

    ms_v1_s = _to_num(df["response_ms_v1"])
    ms_v2_s = _to_num(df["response_ms_v2"])
    ms_v1 = float(ms_v1_s.mean()) if ms_v1_s.notna().any() else None
    ms_v2 = float(ms_v2_s.mean()) if ms_v2_s.notna().any() else None

    src_v1_s = _to_num(df["structured_available_source_ratio_v1"])
    src_v2_s = _to_num(df["structured_available_source_ratio_v2"])

    breve, impacto, riesgo, recomendacion = _smart_conclusion(citation_v1, citation_v2, ms_v1, ms_v2)

    mapping = {
        "{{YYYY-MM-DD}}": dt.date.today().isoformat(),
        "{{NOMBRE}}": args.responsable,
        "{{N}}": str(n_queries),
        "{{N_ESP}}": str(args.expected_queries),
        "{{VAL_V1}}": str(citation_v1),
        "{{VAL_V2}}": str(citation_v2),
        "{{DELTA}}": f"{citation_delta:+d}",
        "{{MS_V1}}": _mean_str(df["response_ms_v1"]),
        "{{MS_V2}}": _mean_str(df["response_ms_v2"]),
        "{{SRC_V1}}": _mean_str(df["structured_available_source_ratio_v1"], digits=3),
        "{{SRC_V2}}": _mean_str(df["structured_available_source_ratio_v2"], digits=3),
        "{{BREVE_CONCLUSION}}": breve,
        "{{IMPACTO}}": impacto,
        "{{RIESGO}}": riesgo,
        "{{RECOMENDACION}}": recomendacion,
    }

    text = template_path.read_text(encoding="utf-8")
    for k, v in mapping.items():
        text = text.replace(k, v)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")

    print(f"[OK] Resumen generado: {out_path}")
    print(f"     Queries: {n_queries}/{args.expected_queries}")
    print(f"     Citation tags: {citation_v1} -> {citation_v2} (delta {citation_delta:+d})")


if __name__ == "__main__":
    main()
